### ISSUE TITLE
Image de l'article

### ISSUE THREAD

**Issue by ouafnico** [Philippe-M/responsee#26]
Bonjour

Les images données comme miniatures pour l'article ont l'air redimensionnées. 
Est-il possible de ne pas les redimensionner, ou pouvoir choisir la taille ?

Merci

**Comment by Philippe-M** [comment]
Bonjour,

La dimension des images est gérées par le framework mais pas redimenssionner. Est-ce que par hasard tu utilise ckeditor ?

**Comment by ouafnico** [comment]
Oui tout à fait mais ce n'est pas une image dans le texte créé via ckeditor mais celle donnée en miniature pour l'article proposé en dessous du texte, natif avec pluxml.

**Comment by Philippe-M** [comment]
Par défaut l'image est redimensionnée par la class .full-img du fichier responsee.css à 100% de largeur. Il est vrai que c'est pas top pour les images qui sont plus petites que le div qui contient l'article.

**Comment by ouafnico** [comment]
est-ce qu'on peut faire en sorte de corriger ça (je suis pas expert en développement web :s)

**Comment by Philippe-M** [comment]
Tu peux le faire en éditant les pages : home.php, article.php, archives.php, categorie.php, tags.php et tu supprime la class css full-img.

Tes images vont avoir leurs veritable dimenssion. Fait des tests sur plusieurs tailles d'écrans (pc, tablette, téléphone) pour vérifier le comportement.

**Comment by ouafnico** [comment]
Parfait ça marche nickel :-)
Merci !
